//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Widget.Weather.WeatherResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Widget.Weather.WeatherResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chance of rain.
        /// </summary>
        public static string HubChanceOfRain {
            get {
                return ResourceManager.GetString("HubChanceOfRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feels like:.
        /// </summary>
        public static string HubFeelsLike {
            get {
                return ResourceManager.GetString("HubFeelsLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string HubLowTemp {
            get {
                return ResourceManager.GetString("HubLowTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Mosaic.
        /// </summary>
        public static string OptionsAbout {
            get {
                return ResourceManager.GetString("OptionsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Weather widget.
        /// </summary>
        public static string OptionsAbout1 {
            get {
                return ResourceManager.GetString("OptionsAbout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some icons provided by Austin Andrews, Ludacris and janek2012..
        /// </summary>
        public static string OptionsAboutIcons {
            get {
                return ResourceManager.GetString("OptionsAboutIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string OptionsAboutTabHeader {
            get {
                return ResourceManager.GetString("OptionsAboutTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string OptionsAboutTabHeader1 {
            get {
                return ResourceManager.GetString("OptionsAboutTabHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apply.
        /// </summary>
        public static string OptionsApplyButton {
            get {
                return ResourceManager.GetString("OptionsApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apply.
        /// </summary>
        public static string OptionsApplyButton1 {
            get {
                return ResourceManager.GetString("OptionsApplyButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart.
        /// </summary>
        public static string OptionsAutostart {
            get {
                return ResourceManager.GetString("OptionsAutostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Mosaic automatically with Windows.
        /// </summary>
        public static string OptionsAutostartCheckBox {
            get {
                return ResourceManager.GetString("OptionsAutostartCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviour.
        /// </summary>
        public static string OptionsBehaviour {
            get {
                return ResourceManager.GetString("OptionsBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        public static string OptionsBg {
            get {
                return ResourceManager.GetString("OptionsBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background image.
        /// </summary>
        public static string OptionsBgImage {
            get {
                return ResourceManager.GetString("OptionsBgImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background image opacity:.
        /// </summary>
        public static string OptionsBgOpacity {
            get {
                return ResourceManager.GetString("OptionsBgOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string OptionsCancelButton {
            get {
                return ResourceManager.GetString("OptionsCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string OptionsCancelButton1 {
            get {
                return ResourceManager.GetString("OptionsCancelButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celsius.
        /// </summary>
        public static string OptionsCelsius {
            get {
                return ResourceManager.GetString("OptionsCelsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        public static string OptionsChange {
            get {
                return ResourceManager.GetString("OptionsChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is protected by copyright law and distributed under Microsoft Public License..
        /// </summary>
        public static string OptionsCopyright {
            get {
                return ResourceManager.GetString("OptionsCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string OptionsData {
            get {
                return ResourceManager.GetString("OptionsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable widget animation.
        /// </summary>
        public static string OptionsEnableAnimation {
            get {
                return ResourceManager.GetString("OptionsEnableAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable windows thumbnails bar.
        /// </summary>
        public static string OptionsEnableThumbBar {
            get {
                return ResourceManager.GetString("OptionsEnableThumbBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable fullscreen mode.
        /// </summary>
        public static string OptionsExclusiveMode {
            get {
                return ResourceManager.GetString("OptionsExclusiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahrenheit.
        /// </summary>
        public static string OptionsFahrenheit {
            get {
                return ResourceManager.GetString("OptionsFahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string OptionsGeneralTabHeader {
            get {
                return ResourceManager.GetString("OptionsGeneralTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string OptionsGeneralTabHeader1 {
            get {
                return ResourceManager.GetString("OptionsGeneralTabHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h..
        /// </summary>
        public static string OptionsIntervalHours {
            get {
                return ResourceManager.GetString("OptionsIntervalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min..
        /// </summary>
        public static string OptionsIntervalMinutes {
            get {
                return ResourceManager.GetString("OptionsIntervalMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsItem {
            get {
                return ResourceManager.GetString("OptionsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string OptionsLanguage {
            get {
                return ResourceManager.GetString("OptionsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string OptionsLocation {
            get {
                return ResourceManager.GetString("OptionsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show menu button.
        /// </summary>
        public static string OptionsMenuButton {
            get {
                return ResourceManager.GetString("OptionsMenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string OptionsOkButton {
            get {
                return ResourceManager.GetString("OptionsOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string OptionsOkButton1 {
            get {
                return ResourceManager.GetString("OptionsOkButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will be applied after restarting Mosaic..
        /// </summary>
        public static string OptionsRestart {
            get {
                return ResourceManager.GetString("OptionsRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll background image when scrolling Mosaic.
        /// </summary>
        public static string OptionsScrollBg {
            get {
                return ResourceManager.GetString("OptionsScrollBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the name of your location and press search.
        /// </summary>
        public static string OptionsSearchBox {
            get {
                return ResourceManager.GetString("OptionsSearchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string OptionsSearchButton {
            get {
                return ResourceManager.GetString("OptionsSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &quot;feels like&quot; temperature instead of actual.
        /// </summary>
        public static string OptionsShowFeelsLike {
            get {
                return ResourceManager.GetString("OptionsShowFeelsLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Windows taskbar in fullscreen mode.
        /// </summary>
        public static string OptionsShowTaskbar {
            get {
                return ResourceManager.GetString("OptionsShowTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show temperature in:.
        /// </summary>
        public static string OptionsShowTempIn {
            get {
                return ResourceManager.GetString("OptionsShowTempIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show weather video in the hub.
        /// </summary>
        public static string OptionsShowVideo {
            get {
                return ResourceManager.GetString("OptionsShowVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show startup animation.
        /// </summary>
        public static string OptionsStartupAnim {
            get {
                return ResourceManager.GetString("OptionsStartupAnim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string OptionsTitle {
            get {
                return ResourceManager.GetString("OptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string OptionsTitle1 {
            get {
                return ResourceManager.GetString("OptionsTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User interface.
        /// </summary>
        public static string OptionsUI {
            get {
                return ResourceManager.GetString("OptionsUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI.
        /// </summary>
        public static string OptionsUI1 {
            get {
                return ResourceManager.GetString("OptionsUI1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI.
        /// </summary>
        public static string OptionsUITabHeader {
            get {
                return ResourceManager.GetString("OptionsUITabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string OptionsVersion {
            get {
                return ResourceManager.GetString("OptionsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string OptionsVersion1 {
            get {
                return ResourceManager.GetString("OptionsVersion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather refresh interval:.
        /// </summary>
        public static string OptionsWeatherInterval {
            get {
                return ResourceManager.GetString("OptionsWeatherInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mosaic options.
        /// </summary>
        public static string OptionsWindowTitle {
            get {
                return ResourceManager.GetString("OptionsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather options.
        /// </summary>
        public static string OptionsWindowTitle1 {
            get {
                return ResourceManager.GetString("OptionsWindowTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string PeopleHubAll {
            get {
                return ResourceManager.GetString("PeopleHubAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string PeopleHubFavorites {
            get {
                return ResourceManager.GetString("PeopleHubFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select friends that you want to pin on a start screen.
        /// </summary>
        public static string PeopleHubTip {
            get {
                return ResourceManager.GetString("PeopleHubTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friends.
        /// </summary>
        public static string PeopleHubTitle {
            get {
                return ResourceManager.GetString("PeopleHubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshItem {
            get {
                return ResourceManager.GetString("RefreshItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshItem1 {
            get {
                return ResourceManager.GetString("RefreshItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveItem {
            get {
                return ResourceManager.GetString("RemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup your location in options. Click to open options..
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back.
        /// </summary>
        public static string ToolbarBackItem {
            get {
                return ResourceManager.GetString("ToolbarBackItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit.
        /// </summary>
        public static string ToolbarExitItem {
            get {
                return ResourceManager.GetString("ToolbarExitItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to options.
        /// </summary>
        public static string ToolbarOptionsItem {
            get {
                return ResourceManager.GetString("ToolbarOptionsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friends.
        /// </summary>
        public static string ToolbarPeopleItem {
            get {
                return ResourceManager.GetString("ToolbarPeopleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application.
        /// </summary>
        public static string ToolbarPinAppItem {
            get {
                return ResourceManager.GetString("ToolbarPinAppItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin.
        /// </summary>
        public static string ToolbarPinItem {
            get {
                return ResourceManager.GetString("ToolbarPinItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to website.
        /// </summary>
        public static string ToolbarPinWebItem {
            get {
                return ResourceManager.GetString("ToolbarPinWebItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string ToolbarWidgetsItem {
            get {
                return ResourceManager.GetString("ToolbarWidgetsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what&apos;s new?.
        /// </summary>
        public static string WhatsNew {
            get {
                return ResourceManager.GetString("WhatsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content of this widget is visible only in fullscreen mode..
        /// </summary>
        public static string WidgetInvisible {
            get {
                return ResourceManager.GetString("WidgetInvisible", resourceCulture);
            }
        }
    }
}
