//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VH.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VH.Resources.EnumResources", typeof(EnumResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 675.
        /// </summary>
        public static string BatterySize_SixSeventyFive {
            get {
                return ResourceManager.GetString("BatterySize_SixSeventyFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string BatterySize_Ten {
            get {
                return ResourceManager.GetString("BatterySize_Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        public static string BatterySize_Thirteen {
            get {
                return ResourceManager.GetString("BatterySize_Thirteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 312.
        /// </summary>
        public static string BatterySize_ThreeTwelve {
            get {
                return ResourceManager.GetString("BatterySize_ThreeTwelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canal/Tip.
        /// </summary>
        public static string EarMoldDesign_CanalOrTip {
            get {
                return ResourceManager.GetString("EarMoldDesign_CanalOrTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Shell.
        /// </summary>
        public static string EarMoldDesign_FullShell {
            get {
                return ResourceManager.GetString("EarMoldDesign_FullShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half Shell.
        /// </summary>
        public static string EarMoldDesign_HalfShell {
            get {
                return ResourceManager.GetString("EarMoldDesign_HalfShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half Skeleton.
        /// </summary>
        public static string EarMoldDesign_HalfSkeleton {
            get {
                return ResourceManager.GetString("EarMoldDesign_HalfSkeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life Tube Mold.
        /// </summary>
        public static string EarMoldDesign_LifeTubeMold {
            get {
                return ResourceManager.GetString("EarMoldDesign_LifeTubeMold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenEar/CROS.
        /// </summary>
        public static string EarMoldDesign_OpenEarOrCROS {
            get {
                return ResourceManager.GetString("EarMoldDesign_OpenEarOrCROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter Skeleton.
        /// </summary>
        public static string EarMoldDesign_QuarterSkeleton {
            get {
                return ResourceManager.GetString("EarMoldDesign_QuarterSkeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver Mold.
        /// </summary>
        public static string EarMoldDesign_ReceiverMold {
            get {
                return ResourceManager.GetString("EarMoldDesign_ReceiverMold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIC Mold.
        /// </summary>
        public static string EarMoldDesign_RICMold {
            get {
                return ResourceManager.GetString("EarMoldDesign_RICMold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skeleton.
        /// </summary>
        public static string EarMoldDesign_Skeleton {
            get {
                return ResourceManager.GetString("EarMoldDesign_Skeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swin Plug.
        /// </summary>
        public static string EarMoldDesign_SwinPlug {
            get {
                return ResourceManager.GetString("EarMoldDesign_SwinPlug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behind the Ear.
        /// </summary>
        public static string EarMoldHearingAidType_BTE {
            get {
                return ResourceManager.GetString("EarMoldHearingAidType_BTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocket.
        /// </summary>
        public static string EarMoldHearingAidType_PKT {
            get {
                return ResourceManager.GetString("EarMoldHearingAidType_PKT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Door.
        /// </summary>
        public static string HearingAidCondition_BatteryDoor {
            get {
                return ResourceManager.GetString("HearingAidCondition_BatteryDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Case.
        /// </summary>
        public static string HearingAidCondition_BodyCase {
            get {
                return ResourceManager.GetString("HearingAidCondition_BodyCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead.
        /// </summary>
        public static string HearingAidCondition_Dead {
            get {
                return ResourceManager.GetString("HearingAidCondition_Dead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distortion.
        /// </summary>
        public static string HearingAidCondition_Distortion {
            get {
                return ResourceManager.GetString("HearingAidCondition_Distortion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Plate Gumming.
        /// </summary>
        public static string HearingAidCondition_FacePlateGumming {
            get {
                return ResourceManager.GetString("HearingAidCondition_FacePlateGumming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string HearingAidCondition_Feedback {
            get {
                return ResourceManager.GetString("HearingAidCondition_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.A. Broken.
        /// </summary>
        public static string HearingAidCondition_HABroken {
            get {
                return ResourceManager.GetString("HearingAidCondition_HABroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hook.
        /// </summary>
        public static string HearingAidCondition_Hook {
            get {
                return ResourceManager.GetString("HearingAidCondition_Hook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermittent.
        /// </summary>
        public static string HearingAidCondition_Intermittent {
            get {
                return ResourceManager.GetString("HearingAidCondition_Intermittent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise.
        /// </summary>
        public static string HearingAidCondition_Noise {
            get {
                return ResourceManager.GetString("HearingAidCondition_Noise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string HearingAidCondition_Others {
            get {
                return ResourceManager.GetString("HearingAidCondition_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Button.
        /// </summary>
        public static string HearingAidCondition_ProgramButton {
            get {
                return ResourceManager.GetString("HearingAidCondition_ProgramButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullingThread.
        /// </summary>
        public static string HearingAidCondition_PullingThread {
            get {
                return ResourceManager.GetString("HearingAidCondition_PullingThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReShelling.
        /// </summary>
        public static string HearingAidCondition_ReShelling {
            get {
                return ResourceManager.GetString("HearingAidCondition_ReShelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicing.
        /// </summary>
        public static string HearingAidCondition_Servicing {
            get {
                return ResourceManager.GetString("HearingAidCondition_Servicing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        public static string HearingAidCondition_Switch {
            get {
                return ResourceManager.GetString("HearingAidCondition_Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimmer.
        /// </summary>
        public static string HearingAidCondition_Trimmer {
            get {
                return ResourceManager.GetString("HearingAidCondition_Trimmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volumn Control.
        /// </summary>
        public static string HearingAidCondition_VolumnControl {
            get {
                return ResourceManager.GetString("HearingAidCondition_VolumnControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wax Gaurd Sitting.
        /// </summary>
        public static string HearingAidCondition_WaxGaurdSitting {
            get {
                return ResourceManager.GetString("HearingAidCondition_WaxGaurdSitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak.
        /// </summary>
        public static string HearingAidCondition_Weak {
            get {
                return ResourceManager.GetString("HearingAidCondition_Weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elbow Replacement.
        /// </summary>
        public static string MoldRepair_ElbowReplacement {
            get {
                return ResourceManager.GetString("MoldRepair_ElbowReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lacquering.
        /// </summary>
        public static string MoldRepair_Lacquering {
            get {
                return ResourceManager.GetString("MoldRepair_Lacquering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retubing.
        /// </summary>
        public static string MoldRepair_Retubing {
            get {
                return ResourceManager.GetString("MoldRepair_Retubing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimming.
        /// </summary>
        public static string MoldRepair_Trimming {
            get {
                return ResourceManager.GetString("MoldRepair_Trimming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        public static string OrderStatus_Delivered {
            get {
                return ResourceManager.GetString("OrderStatus_Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Process.
        /// </summary>
        public static string OrderStatus_InProcess {
            get {
                return ResourceManager.GetString("OrderStatus_InProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Taken.
        /// </summary>
        public static string OrderStatus_OrderTaken {
            get {
                return ResourceManager.GetString("OrderStatus_OrderTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Dispatched.
        /// </summary>
        public static string RepairStatus_CompanyDispatched {
            get {
                return ResourceManager.GetString("RepairStatus_CompanyDispatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Received.
        /// </summary>
        public static string RepairStatus_CompanyReceived {
            get {
                return ResourceManager.GetString("RepairStatus_CompanyReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered To Customer.
        /// </summary>
        public static string RepairStatus_DeliveredToCustomer {
            get {
                return ResourceManager.GetString("RepairStatus_DeliveredToCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatched To Company.
        /// </summary>
        public static string RepairStatus_DispatchedToCompany {
            get {
                return ResourceManager.GetString("RepairStatus_DispatchedToCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Processed.
        /// </summary>
        public static string RepairStatus_NotProcessed {
            get {
                return ResourceManager.GetString("RepairStatus_NotProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string RepairStatus_Received {
            get {
                return ResourceManager.GetString("RepairStatus_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libby Horn.
        /// </summary>
        public static string SoftMoldTubingType_LibbyHorn {
            get {
                return ResourceManager.GetString("SoftMoldTubingType_LibbyHorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        public static string SoftMoldTubingType_Regular {
            get {
                return ResourceManager.GetString("SoftMoldTubingType_Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        public static string VentSize_One {
            get {
                return ResourceManager.GetString("VentSize_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.5.
        /// </summary>
        public static string VentSize_OnePoint5 {
            get {
                return ResourceManager.GetString("VentSize_OnePoint5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .5.
        /// </summary>
        public static string VentSize_Point5 {
            get {
                return ResourceManager.GetString("VentSize_Point5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.0.
        /// </summary>
        public static string VentSize_Three {
            get {
                return ResourceManager.GetString("VentSize_Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.0.
        /// </summary>
        public static string VentSize_Two {
            get {
                return ResourceManager.GetString("VentSize_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.5.
        /// </summary>
        public static string VentSize_TwoPoint5 {
            get {
                return ResourceManager.GetString("VentSize_TwoPoint5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Warranty.
        /// </summary>
        public static string WarrantyType_NonWarranty {
            get {
                return ResourceManager.GetString("WarrantyType_NonWarranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty.
        /// </summary>
        public static string WarrantyType_Warranty {
            get {
                return ResourceManager.GetString("WarrantyType_Warranty", resourceCulture);
            }
        }
    }
}
