//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VH.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LabelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LabelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VH.Resources.LabelResources", typeof(LabelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCESSORIES RECEIVED.
        /// </summary>
        public static string AccessoriesReceived {
            get {
                return ResourceManager.GetString("AccessoriesReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDITIONAL COMMENT.
        /// </summary>
        public static string AdditionalComment {
            get {
                return ResourceManager.GetString("AdditionalComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD NEW CUSTOMER.
        /// </summary>
        public static string AddNewCustomer {
            get {
                return ResourceManager.GetString("AddNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDRESS : .
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDRESS DETAILS.
        /// </summary>
        public static string AddressDetails {
            get {
                return ResourceManager.GetString("AddressDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDRESS(s).
        /// </summary>
        public static string ADDRESSs {
            get {
                return ResourceManager.GetString("ADDRESSs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADV AMT RECEIVED.
        /// </summary>
        public static string AdvanceAmount {
            get {
                return ResourceManager.GetString("AdvanceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AID TYPE.
        /// </summary>
        public static string AidType {
            get {
                return ResourceManager.GetString("AidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMOUNT.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPOINTMENT.
        /// </summary>
        public static string Appointment {
            get {
                return ResourceManager.GetString("Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN TIME.
        /// </summary>
        public static string AppointmentBeginTime {
            get {
                return ResourceManager.GetString("AppointmentBeginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END TIME.
        /// </summary>
        public static string AppointmentEndTime {
            get {
                return ResourceManager.GetString("AppointmentEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPOINTMENTTIME.
        /// </summary>
        public static string AppointmentTime {
            get {
                return ResourceManager.GetString("AppointmentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE.
        /// </summary>
        public static string AppointmentType {
            get {
                return ResourceManager.GetString("AppointmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BALANCE AMT.
        /// </summary>
        public static string BalanceAmount {
            get {
                return ResourceManager.GetString("BalanceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BATTERY SIZE.
        /// </summary>
        public static string BatterySize {
            get {
                return ResourceManager.GetString("BatterySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALL DATE.
        /// </summary>
        public static string CallDate {
            get {
                return ResourceManager.GetString("CallDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALLER NAME.
        /// </summary>
        public static string CallerName {
            get {
                return ResourceManager.GetString("CallerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALL TIME.
        /// </summary>
        public static string CallTime {
            get {
                return ResourceManager.GetString("CallTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CITY : .
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMENT.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPANY.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPANY DISPATCHED.
        /// </summary>
        public static string CompanyDispatcedDate {
            get {
                return ResourceManager.GetString("CompanyDispatcedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPANY RECEIVED.
        /// </summary>
        public static string CompanyReceivedDate {
            get {
                return ResourceManager.GetString("CompanyReceivedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLAINT DESCRIPTION.
        /// </summary>
        public static string ComplaintDesc {
            get {
                return ResourceManager.GetString("ComplaintDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLAINT DESC.
        /// </summary>
        public static string ComplaintDescription {
            get {
                return ResourceManager.GetString("ComplaintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM PASSWORD.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNTRY : .
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create new account.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPR ON ESTIMATE AMT.
        /// </summary>
        public static string CustomerApprovalOnEstimateAmt {
            get {
                return ResourceManager.GetString("CustomerApprovalOnEstimateAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA SAVED.
        /// </summary>
        public static string DataSaved {
            get {
                return ResourceManager.GetString("DataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELIVERED DATE.
        /// </summary>
        public static string DeliveredDate {
            get {
                return ResourceManager.GetString("DeliveredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELIVERED TO CUSTOMER.
        /// </summary>
        public static string DeliveredToCustomerDate {
            get {
                return ResourceManager.GetString("DeliveredToCustomerDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISPATCHED TO COMPANY.
        /// </summary>
        public static string DispatchedToCompanyDate {
            get {
                return ResourceManager.GetString("DispatchedToCompanyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOB : .
        /// </summary>
        public static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUE DATE.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAR MOLD.
        /// </summary>
        public static string EarMold {
            get {
                return ResourceManager.GetString("EarMold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOLD DESIGN.
        /// </summary>
        public static string EarMoldDesign {
            get {
                return ResourceManager.GetString("EarMoldDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOLD TYPE.
        /// </summary>
        public static string EarMoldType {
            get {
                return ResourceManager.GetString("EarMoldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIDE.
        /// </summary>
        public static string EarSide {
            get {
                return ResourceManager.GetString("EarSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT APPOINTMENT.
        /// </summary>
        public static string EditAppointment {
            get {
                return ResourceManager.GetString("EditAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL :.
        /// </summary>
        public static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXISTING CUSTOMER.
        /// </summary>
        public static string ExistingCustomer {
            get {
                return ResourceManager.GetString("ExistingCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRSTNAME : .
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forgot your password.
        /// </summary>
        public static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENDER : .
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDRESS.
        /// </summary>
        public static string GridAddress {
            get {
                return ResourceManager.GetString("GridAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE OF BIRTH.
        /// </summary>
        public static string GridDOB {
            get {
                return ResourceManager.GetString("GridDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        public static string GridEmail {
            get {
                return ResourceManager.GetString("GridEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        public static string GridFormattedName {
            get {
                return ResourceManager.GetString("GridFormattedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENDER.
        /// </summary>
        public static string GridGender {
            get {
                return ResourceManager.GetString("GridGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMBER.
        /// </summary>
        public static string GridPhoneNumber {
            get {
                return ResourceManager.GetString("GridPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEARING AID.
        /// </summary>
        public static string HearingAid {
            get {
                return ResourceManager.GetString("HearingAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEARING AID CONDITION.
        /// </summary>
        public static string HearingAidCondition {
            get {
                return ResourceManager.GetString("HearingAidCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AID ID.
        /// </summary>
        public static string HearingAidId {
            get {
                return ResourceManager.GetString("HearingAidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEARING AID TYPE.
        /// </summary>
        public static string HearingAidType {
            get {
                return ResourceManager.GetString("HearingAidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMATION.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMED DATE.
        /// </summary>
        public static string InformedDate {
            get {
                return ResourceManager.GetString("InformedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS ADMIN.
        /// </summary>
        public static string IsAdmin {
            get {
                return ResourceManager.GetString("IsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISPRIMARY : .
        /// </summary>
        public static string IsPrimary {
            get {
                return ResourceManager.GetString("IsPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LASTNAME : .
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEFT.
        /// </summary>
        public static string left {
            get {
                return ResourceManager.GetString("left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN NAME.
        /// </summary>
        public static string LoginName {
            get {
                return ResourceManager.GetString("LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN PASSWORD.
        /// </summary>
        public static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MESSAGE.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODEL.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODEL LEFT.
        /// </summary>
        public static string Model_Left {
            get {
                return ResourceManager.GetString("Model_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODEL RIGHT.
        /// </summary>
        public static string Model_Right {
            get {
                return ResourceManager.GetString("Model_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOLDS.
        /// </summary>
        public static string Molds {
            get {
                return ResourceManager.GetString("Molds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW PASSWORD.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO..
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLD PASSWORD .
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER DATE.
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDERS - EAR MOLD.
        /// </summary>
        public static string OrderEarMold {
            get {
                return ResourceManager.GetString("OrderEarMold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDERS - HEARING AID.
        /// </summary>
        public static string OrderHeardingAid {
            get {
                return ResourceManager.GetString("OrderHeardingAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER ID.
        /// </summary>
        public static string OrderID {
            get {
                return ResourceManager.GetString("OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        public static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHONE DETAILS.
        /// </summary>
        public static string PhoneDetails {
            get {
                return ResourceManager.GetString("PhoneDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHONE NO. : .
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHONE TYPE : .
        /// </summary>
        public static string PhoneType {
            get {
                return ResourceManager.GetString("PhoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECEIVED DATE.
        /// </summary>
        public static string ReceivedDate {
            get {
                return ResourceManager.GetString("ReceivedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFRESH.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R,SHIP.
        /// </summary>
        public static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember my password.
        /// </summary>
        public static string RememberPassword {
            get {
                return ResourceManager.GetString("RememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMINDERS.
        /// </summary>
        public static string Reminders {
            get {
                return ResourceManager.GetString("Reminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPAIR AMT LESS THAN.
        /// </summary>
        public static string RepairAmtLessThan {
            get {
                return ResourceManager.GetString("RepairAmtLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPAIR ID.
        /// </summary>
        public static string RepairID {
            get {
                return ResourceManager.GetString("RepairID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPAIR LIST.
        /// </summary>
        public static string RepairList {
            get {
                return ResourceManager.GetString("RepairList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPAIR STATUS.
        /// </summary>
        public static string RepairStatus {
            get {
                return ResourceManager.GetString("RepairStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVISED SL NO.,.
        /// </summary>
        public static string RevisedSerialNumber {
            get {
                return ResourceManager.GetString("RevisedSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIGHT.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH CUSTOMER.
        /// </summary>
        public static string SearchCustomer {
            get {
                return ResourceManager.GetString("SearchCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERIAL NUMBER.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SL No. LEFT.
        /// </summary>
        public static string SerialNumberL {
            get {
                return ResourceManager.GetString("SerialNumberL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERIAL NO. LEFT.
        /// </summary>
        public static string SerialNumberLeft {
            get {
                return ResourceManager.GetString("SerialNumberLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SL No. RIGHT.
        /// </summary>
        public static string SerialNumberR {
            get {
                return ResourceManager.GetString("SerialNumberR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERIAL NO. RIGHT.
        /// </summary>
        public static string SerialNumberRight {
            get {
                return ResourceManager.GetString("SerialNumberRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign me in automatically.
        /// </summary>
        public static string SignMe {
            get {
                return ResourceManager.GetString("SignMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TUBING TYPE.
        /// </summary>
        public static string SoftMoldTubingType {
            get {
                return ResourceManager.GetString("SoftMoldTubingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPARE AID GIVEN.
        /// </summary>
        public static string SpareAidGiven {
            get {
                return ResourceManager.GetString("SpareAidGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPARE AID DETAILS.
        /// </summary>
        public static string SpareAidGivenDetails {
            get {
                return ResourceManager.GetString("SpareAidGivenDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPARE AID RECEIVED.
        /// </summary>
        public static string SpareAidReceived {
            get {
                return ResourceManager.GetString("SpareAidReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATE : .
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIME.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE STATUS.
        /// </summary>
        public static string UpdateRepairStatus {
            get {
                return ResourceManager.GetString("UpdateRepairStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USERNAME.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VENT LENGTH.
        /// </summary>
        public static string VentLength {
            get {
                return ResourceManager.GetString("VentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VENT SIZE.
        /// </summary>
        public static string VentSize {
            get {
                return ResourceManager.GetString("VentSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VENT TYPE.
        /// </summary>
        public static string VentType {
            get {
                return ResourceManager.GetString("VentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VH ERP.
        /// </summary>
        public static string VHERP {
            get {
                return ResourceManager.GetString("VHERP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECEIVED DATE.
        /// </summary>
        public static string VHReceivedDate {
            get {
                return ResourceManager.GetString("VHReceivedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARRANTY CARD WITH.
        /// </summary>
        public static string WarrantyCardGiven {
            get {
                return ResourceManager.GetString("WarrantyCardGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARRANTY TYPE.
        /// </summary>
        public static string WarrantyType {
            get {
                return ResourceManager.GetString("WarrantyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIPCODE : .
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
