//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VH.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VH.Resources.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the window?.
        /// </summary>
        public static string CancelWindowMessage {
            get {
                return ResourceManager.GetString("CancelWindowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear details?.
        /// </summary>
        public static string ClearMessage {
            get {
                return ResourceManager.GetString("ClearMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Save Failed.
        /// </summary>
        public static string DataSavedFailed {
            get {
                return ResourceManager.GetString("DataSavedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Saved Successfull.
        /// </summary>
        public static string DataSavedSuccessfully {
            get {
                return ResourceManager.GetString("DataSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected record(s) deleted successfully.
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected record(s)?.
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected record(s) cannot be deleted .
        /// </summary>
        public static string DeletionFailed {
            get {
                return ResourceManager.GetString("DeletionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment can only be added on current/furture date.
        /// </summary>
        public static string InvalidAppointmentDate {
            get {
                return ResourceManager.GetString("InvalidAppointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet Delivered.
        /// </summary>
        public static string NotYetDelivered {
            get {
                return ResourceManager.GetString("NotYetDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet Informed.
        /// </summary>
        public static string NotYetInformed {
            get {
                return ResourceManager.GetString("NotYetInformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet Received.
        /// </summary>
        public static string NotYetReceived {
            get {
                return ResourceManager.GetString("NotYetReceived", resourceCulture);
            }
        }
    }
}
