//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VH.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TitleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TitleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VH.Resources.TitleResources", typeof(TitleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD APPOINTMENT.
        /// </summary>
        public static string AddAppointment {
            get {
                return ResourceManager.GetString("AddAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD CALL LOG.
        /// </summary>
        public static string AddCallLog {
            get {
                return ResourceManager.GetString("AddCallLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD EAR MOLD ORDER.
        /// </summary>
        public static string AddCustomerEarMoldOrder {
            get {
                return ResourceManager.GetString("AddCustomerEarMoldOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD HEARING AID ORDER.
        /// </summary>
        public static string AddCustomerHearingAidOrder {
            get {
                return ResourceManager.GetString("AddCustomerHearingAidOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD CUSTOMER REPAIR.
        /// </summary>
        public static string AddCustomerRepair {
            get {
                return ResourceManager.GetString("AddCustomerRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD NEW CUSTOMER.
        /// </summary>
        public static string AddNewCustomer {
            get {
                return ResourceManager.GetString("AddNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD REMINDER.
        /// </summary>
        public static string AddReminder {
            get {
                return ResourceManager.GetString("AddReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD USER LOGIN.
        /// </summary>
        public static string AddUserLogin {
            get {
                return ResourceManager.GetString("AddUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD WARRANTY INFORMED.
        /// </summary>
        public static string AddWarrantyInformed {
            get {
                return ResourceManager.GetString("AddWarrantyInformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOMER : {0}.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT CALL LOG.
        /// </summary>
        public static string EditCallLog {
            get {
                return ResourceManager.GetString("EditCallLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT CUSTOMER.
        /// </summary>
        public static string EditCustomer {
            get {
                return ResourceManager.GetString("EditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT EAR MOLD ORDER.
        /// </summary>
        public static string EditCustomerEarMoldOrder {
            get {
                return ResourceManager.GetString("EditCustomerEarMoldOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT HEARING AID ORDER.
        /// </summary>
        public static string EditCustomerHearingAidOrder {
            get {
                return ResourceManager.GetString("EditCustomerHearingAidOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT CUSTOMER REPAIR.
        /// </summary>
        public static string EditCustomerRepair {
            get {
                return ResourceManager.GetString("EditCustomerRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT REMINDER.
        /// </summary>
        public static string EditReminder {
            get {
                return ResourceManager.GetString("EditReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT USER LOGIN.
        /// </summary>
        public static string EditUserLogin {
            get {
                return ResourceManager.GetString("EditUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT WARRANTY INFORMED.
        /// </summary>
        public static string EditWarrantyInformed {
            get {
                return ResourceManager.GetString("EditWarrantyInformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMATION.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRINT.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE REPAIR STATUS.
        /// </summary>
        public static string UpdateRepairStatus {
            get {
                return ResourceManager.GetString("UpdateRepairStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAIBHAV SPEECH &amp; HEARING CENTER.
        /// </summary>
        public static string VHERP {
            get {
                return ResourceManager.GetString("VHERP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
