//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VH.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TooltipResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TooltipResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VH.Resources.TooltipResources", typeof(TooltipResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        public static string ADD {
            get {
                return ResourceManager.GetString("ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD APPOINTMENT.
        /// </summary>
        public static string AddAppointment {
            get {
                return ResourceManager.GetString("AddAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD CALL LOG.
        /// </summary>
        public static string AddCallLog {
            get {
                return ResourceManager.GetString("AddCallLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD CUSTOMER.
        /// </summary>
        public static string AddCustomer {
            get {
                return ResourceManager.GetString("AddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD EAR MOLD.
        /// </summary>
        public static string AddEarMold {
            get {
                return ResourceManager.GetString("AddEarMold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD HEARING AID.
        /// </summary>
        public static string AddHearingAid {
            get {
                return ResourceManager.GetString("AddHearingAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD REMINDER.
        /// </summary>
        public static string AddReminder {
            get {
                return ResourceManager.GetString("AddReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check to Delete the record.
        /// </summary>
        public static string CheckToDelete {
            get {
                return ResourceManager.GetString("CheckToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE APPOINTMENT.
        /// </summary>
        public static string DeleteAppointment {
            get {
                return ResourceManager.GetString("DeleteAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE CALL LOG.
        /// </summary>
        public static string DeleteCallLog {
            get {
                return ResourceManager.GetString("DeleteCallLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE CUSTOMER.
        /// </summary>
        public static string DeleteCustomer {
            get {
                return ResourceManager.GetString("DeleteCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE EAR MOLD.
        /// </summary>
        public static string DeleteEarMold {
            get {
                return ResourceManager.GetString("DeleteEarMold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE HEARING AID.
        /// </summary>
        public static string DeleteHearingAid {
            get {
                return ResourceManager.GetString("DeleteHearingAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE REMINDER.
        /// </summary>
        public static string DeleteReminder {
            get {
                return ResourceManager.GetString("DeleteReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT APPOINTMENT.
        /// </summary>
        public static string EditAppointment {
            get {
                return ResourceManager.GetString("EditAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT CALL LOG.
        /// </summary>
        public static string EditCallLog {
            get {
                return ResourceManager.GetString("EditCallLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT CUSTOMER.
        /// </summary>
        public static string EditCustomer {
            get {
                return ResourceManager.GetString("EditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT EAR MOLD.
        /// </summary>
        public static string EditEarMold {
            get {
                return ResourceManager.GetString("EditEarMold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT HEARING AID.
        /// </summary>
        public static string EditHearingAid {
            get {
                return ResourceManager.GetString("EditHearingAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT REMINDER.
        /// </summary>
        public static string EditReminder {
            get {
                return ResourceManager.GetString("EditReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate Back.
        /// </summary>
        public static string NaviagteBack {
            get {
                return ResourceManager.GetString("NaviagteBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRINT.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFRESH EAR MOLD.
        /// </summary>
        public static string RefereshEarMold {
            get {
                return ResourceManager.GetString("RefereshEarMold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFRESH.
        /// </summary>
        public static string RefreshCustomer {
            get {
                return ResourceManager.GetString("RefreshCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFRESH HEARING AID.
        /// </summary>
        public static string RefreshHearingAid {
            get {
                return ResourceManager.GetString("RefreshHearingAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE STATUS.
        /// </summary>
        public static string UpdateRepairStatus {
            get {
                return ResourceManager.GetString("UpdateRepairStatus", resourceCulture);
            }
        }
    }
}
